
package SOAP.client.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import SOAP.endpoints.ReviewServiceInterface;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BroadwayServiceService", targetNamespace = "http://endpoints.SOAP/", wsdlLocation = "http://localhost:8888/PA3/broadway?wsdl")
public class BroadwayServiceService
    extends Service
{

    private final static URL BROADWAYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BROADWAYSERVICESERVICE_EXCEPTION;
    private final static QName BROADWAYSERVICESERVICE_QNAME = new QName("http://endpoints.SOAP/", "BroadwayServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/PA3/broadway?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BROADWAYSERVICESERVICE_WSDL_LOCATION = url;
        BROADWAYSERVICESERVICE_EXCEPTION = e;
    }

    public BroadwayServiceService() {
        super(__getWsdlLocation(), BROADWAYSERVICESERVICE_QNAME);
    }

    public BroadwayServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BROADWAYSERVICESERVICE_QNAME, features);
    }

    public BroadwayServiceService(URL wsdlLocation) {
        super(wsdlLocation, BROADWAYSERVICESERVICE_QNAME);
    }

    public BroadwayServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BROADWAYSERVICESERVICE_QNAME, features);
    }

    public BroadwayServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BroadwayServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReviewServiceInterface
     */
    @WebEndpoint(name = "BroadwayServicePort")
    public ReviewServiceInterface getBroadwayServicePort() {
        return super.getPort(new QName("http://endpoints.SOAP/", "BroadwayServicePort"), ReviewServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReviewServiceInterface
     */
    @WebEndpoint(name = "BroadwayServicePort")
    public ReviewServiceInterface getBroadwayServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoints.SOAP/", "BroadwayServicePort"), ReviewServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BROADWAYSERVICESERVICE_EXCEPTION!= null) {
            throw BROADWAYSERVICESERVICE_EXCEPTION;
        }
        return BROADWAYSERVICESERVICE_WSDL_LOCATION;
    }

}
