
package SOAP.client.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import SOAP.endpoints.ReviewServiceInterface;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlaybillServiceService", targetNamespace = "http://endpoints.SOAP/", wsdlLocation = "http://localhost:8888/PA3/playbill?wsdl")
public class PlaybillServiceService
    extends Service
{

    private final static URL PLAYBILLSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PLAYBILLSERVICESERVICE_EXCEPTION;
    private final static QName PLAYBILLSERVICESERVICE_QNAME = new QName("http://endpoints.SOAP/", "PlaybillServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/PA3/playbill?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLAYBILLSERVICESERVICE_WSDL_LOCATION = url;
        PLAYBILLSERVICESERVICE_EXCEPTION = e;
    }

    public PlaybillServiceService() {
        super(__getWsdlLocation(), PLAYBILLSERVICESERVICE_QNAME);
    }

    public PlaybillServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLAYBILLSERVICESERVICE_QNAME, features);
    }

    public PlaybillServiceService(URL wsdlLocation) {
        super(wsdlLocation, PLAYBILLSERVICESERVICE_QNAME);
    }

    public PlaybillServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLAYBILLSERVICESERVICE_QNAME, features);
    }

    public PlaybillServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlaybillServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReviewServiceInterface
     */
    @WebEndpoint(name = "PlaybillServicePort")
    public ReviewServiceInterface getPlaybillServicePort() {
        return super.getPort(new QName("http://endpoints.SOAP/", "PlaybillServicePort"), ReviewServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReviewServiceInterface
     */
    @WebEndpoint(name = "PlaybillServicePort")
    public ReviewServiceInterface getPlaybillServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoints.SOAP/", "PlaybillServicePort"), ReviewServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLAYBILLSERVICESERVICE_EXCEPTION!= null) {
            throw PLAYBILLSERVICESERVICE_EXCEPTION;
        }
        return PLAYBILLSERVICESERVICE_WSDL_LOCATION;
    }

}
