
package SOAP.client.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReviewServiceInterface", targetNamespace = "http://endpoints.SOAP/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReviewServiceInterface {


    /**
     * 
     * @return
     *     returns client.ConcurrentHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoints.SOAP/ReviewServiceInterface/readFileRequest", output = "http://endpoints.SOAP/ReviewServiceInterface/readFileResponse")
    public ConcurrentHashMap readFile();

    /**
     * 
     * @param arg0
     * @return
     *     returns client.ConcurrentHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoints.SOAP/ReviewServiceInterface/getReviewsByDateRequest", output = "http://endpoints.SOAP/ReviewServiceInterface/getReviewsByDateResponse")
    public java.util.concurrent.ConcurrentHashMap<Integer, String[]> getReviewsByDate(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns client.ConcurrentHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoints.SOAP/ReviewServiceInterface/getReviewsByGenreRequest", output = "http://endpoints.SOAP/ReviewServiceInterface/getReviewsByGenreResponse")
    public java.util.concurrent.ConcurrentHashMap<Integer, String[]> getReviewsByGenre(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns client.ConcurrentHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoints.SOAP/ReviewServiceInterface/getReviewsByNameRequest", output = "http://endpoints.SOAP/ReviewServiceInterface/getReviewsByNameResponse")
    public java.util.concurrent.ConcurrentHashMap<Integer, String[]> getReviewsByName(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns client.ConcurrentHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoints.SOAP/ReviewServiceInterface/getAllReviewsRequest", output = "http://endpoints.SOAP/ReviewServiceInterface/getAllReviewsResponse")
    public java.util.concurrent.ConcurrentHashMap<Integer, String[]> getAllReviews();

}
